### PR TITLE
Ensure that failing fread won't cause a hanging process

### LINKED ISSUE #24: Gzip::extract stuck in an endless loop
I managed to download a corrupt .gz file, in which case fread() returns an empty string at some point. This results in an endless loop (using 100% of one core), since the eof will never be reached.

I'm not sure if the same issue exists with bzip.

### PR DESCRIPTION
**Pull request by sgiehl**
### Description:

It may happen that for a corrupted file `fread` may return `false`, while the file end has not yet been reached.

This PR adds a better handling for that case, so extracting won't get stuck.

fixes #24

### CODE REVIEW

File: src/Bzip.php [hunk 1]
```diff
@@ -54,7 +54,14 @@ public function extract($pathExtracted)
 
         $output = fopen($pathExtracted, 'w');
         while (!feof($file)) {
-            fwrite($output, fread($file, 1024 * 1024));
+            $content = fread($file, 1024 * 1024);
+
+            if (false === $content) {
+                $this->error = "fread failed";
+                return false;
```
Comment (mneudert) [inline src/Bzip.php:61]: I expect this to solve the problem.

Only question would be: should we do any explicit cleanup? E.g. delete the "most likely broken" output file? And maybe close all file handles, even though the should (afaik) also be closed by the garbage collection once the function returns?

**Review by mneudert — APPROVED** [review]
